version: '3'
services:
  stubby:
    image: "gittu/stubby-docker:latest"
    ports:
     - "53:8053/udp"
    volumes:
      - ./stubbyconfig:/confg # Edit and make your own config file
    restart: unless-stopped