version: '3'
services:
  stubby:
    image: "sarim/stubby:latest"
    ports:
     - "53:8053/udp"
    volumes:
      - ./stubby/stubby.yaml:/.stubby.yaml # Use your own config file
    restart: unless-stopped